name: Check
on:
  push:
    branches:
      - 'main'
    paths:
      - '**'

jobs:
  build-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
      - name: Add permission to execute gradlew
        run: chmod +x ${{ github.workspace }}/gradlew
      - name: Run Build & Detekt
        run: ./gradlew build detekt
