name: Check
on:
  push:
    branches:
      - 'main'
    paths:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  build-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
      - name: Add permission to execute gradlew
        run: chmod +x ${{ github.workspace }}/gradlew
      - name: Run Build & Detekt
        run: ./gradlew build detekt
