name: Check
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'

jobs:
  build-agent:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest }
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
      - run: gradlew build
